# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: k8s-dev-config
#   namespace: argocd
# spec:
#   project: default
#   source:
#     repoURL: git@github.com:tense-dev/k8s-nonprod-config.git
#     targetRevision: main
#     path: dev
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: default
#   syncPolicy:
#     automated:
#       prune: true